# Generated by Django 5.2.4 on 2025-07-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('content', models.TextField(verbose_name='Content')),
                ('rating', models.IntegerField(default=5, verbose_name='Rating')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Vehicle Name')),
                ('image', models.ImageField(upload_to='vehicles/', verbose_name='Image')),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=20, verbose_name='Transmission')),
                ('air_conditioning', models.BooleanField(default=True, verbose_name='Air Conditioning')),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], max_length=20, verbose_name='Fuel Type')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Daily Price (MAD)')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-featured', 'name'],
            },
        ),
    ]
